config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
end

	root to: "blogs#index"
  resources :blogs, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
  resources :comments, only: [:create]
   end
  resources :users, only: [:show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :blogs
         has_many :comments

          validates_uniqueness_of :nickname
          validates_presence_of :nickname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	before_action :redirect_to_index, :except => [:index]

  def index
    @blogs = Blog.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def show
    @blog = Blog.find(params[:id])
    @comments = @blog.comments.includes(:user)
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(image: blog_params[:image], title: blog_params[:title], text: blog_params[:text], user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(id_params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

  def edit
    @blog = Blog.find(id_params[:id])
  end

  def update
    blog = Blog.find(id_params[:id])
    blog.update(blog_params) if blog.user_id == current_user.id
  end

  private
  def blog_params
    params.require(:blog).permit(:image, :text, :title)
  end

  def id_params
    params.permit(:id)
  end

  def redirect_to_index
    redirect_to :action => "index" unless user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @comment = Comment.create(text: comment_params[:text], blog_id: comment_params[:blog_id], user_id: current_user.id)
  	 redirect_to "/blogs/#{@comment.blog.id}"

  end

  private
  def comment_params
    params.permit(:text, :blog_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# def show
 #    user = User.find(show_params[:id])
 #    @nickname = current_user.nickname
 #    @blogs = current_user.blogs.page(params[:page]).per(5).order('created_at DESC')
 #  end

  # private
  # def show_params
  #   params.permit(:id)
  # end

  def show
		user = User.find(params[:id])
	@nickname = user.nickname
	@blogs = user.blogs.page(params[:page]).per(5).order("created_at DESC")

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
  <div class="col s12 m7">
    <div class="card horizontal">
      <div class="card-image">
        <span><%= image_tag 'arrow_top.png' %></span>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>タイトル : <%= blog.title %></p>
          <p>本文 : <%= blog.text %></p>
           <p>ユーザー : <%= blog.user.nickname %></p>
        </div>
        <div class="card-action">
          <ul class="more_list">
          <li>
            <%= link_to "詳細", blog_path(blog.id), method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == blog.user_id %>
            <li>
              <%= link_to '編集', "/blogs/#{blog.id}/edit", method: :get %>
            </li>
            <li>
          <%= button_to '削除', "/blogs/#{blog.id}", method: :delete %>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
  </div>

app/views/blogs/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/blogs/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/edit.html.erb
  <div class="contents row">
<%= form_for(@blog) do |f| %>
      <h3>
        編集する
      </h3>
      <a>タイトル:<%= f.text_field :title %></a>
  <a>テキスト:<%= f.text_area :text %></a>
  <a>画像:<%= f.text_field :image %></a>

  <div class="actions">
     <%= f.submit "編集する" %>
   </div>
  <% end %>
    </div>
  

app/views/blogs/index.html.erb
<div class="contents row">
  <%=render @blogs %>
  <%= paginate(@blogs) %>
</div>

app/views/blogs/new.html.erb
<div class="contents row">
<%= form_for(@blog) do |f| %>
      <h3>
        投稿する
      </h3>
      <a>タイトル:<%= f.text_field :title %></a>
  <a>テキスト:<%= f.text_area :text %></a>
  <a>画像:<%= f.text_field :image %></a>

  <div class="actions">
     <%= f.submit "投稿する" %>
   </div>
  <% end %>
    </div>
  

app/views/blogs/show.html.erb
<div class ="contents row">
  <div class="content__post" style="background-image: url(<%= @blog.image %>);">
    <% if current_user && @blog.user_id == current_user.id %>
      <div class="more"> 
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/blogs/#{@blog.id}/edit", method: :get %>
        </li>
          <li>
            <%= link_to '削除', "/blogs/#{@blog.id}", method: :delete %>
          </li>
      </ul>
      </div>
    <% end %>
    <%= simple_format(@blog.text) %>
    <span class="name">
      <a href="/users/<%= @blog.user_id %>">
        <span>投稿者</span><%= @blog.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_tag("/blogs/#{@blog.id}/comments") do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <storng><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= @comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
 

</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Blog</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <!-- <li><a href="sass.html">ログイン</a></li>
        <li><a href="badges.html">新規登録</a></li>
        <li><a href="/blogs/new">投稿</a></li>
       -->
       <% if user_signed_in? %>
        <div class="user_nav grid-6">
           <li><%= current_user.nickname %></li>
             
                <li><a href="/users/<%= current_user.id %>">マイページ</a></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </li>
         
          <li><a class="post" href="/blogs/new">投稿する</a></li>
        </div>
        <% else %>
        <div class="grid-6">
          <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
        </div>
      <% end %>
      </ul>
</div>
</nav>
    </header>





    <%= yield %>

    <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2019 Blog Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
<script type="text/javascript" src="./app.js"></script>

</body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <%= render @blogs %>
  <%= paginate(@blogs) %>
</div>